#!/usr/bin/env python3
"""
Package a Lyra 1.0 run into a viewer world bundle.

Finds the newest gaussians_*.ply under --out-dir, the frame-0 camera intrinsics
from the GEN3C --gen-dir, and writes bundles/<id>/world.json + copies.

Why this matters for provenance: GEN3C defines the source photo's camera as the
IDENTITY pose (world frame == first camera frame, OpenCV convention) and MoGe
estimates its intrinsics, so unlike Marble we get the photographer's pose *and*
field of view for free. The viewer's "photographer" empty at the splat origin is
therefore exact, not a guess.

  scp -r bundles/<id> laptop:WalkThePast/viewer/public/worlds/
"""
from __future__ import annotations

import argparse
import glob
import json
import math
import os
import shutil
from pathlib import Path

import numpy as np


def newest(paths: list[str]) -> str | None:
    return max(paths, key=os.path.getmtime) if paths else None


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", required=True, type=Path)
    ap.add_argument("--id", required=True)
    ap.add_argument("--gen-dir", default="assets/demo/static/diffusion_output_generated")
    ap.add_argument("--out-dir", default="outputs/walkthepast")
    ap.add_argument("--bundle-dir", default="bundles")
    ap.add_argument("--ply", help="explicit ply path (skips auto-discovery)")
    args = ap.parse_args()

    ply = args.ply or newest(glob.glob(f"{args.out_dir}/**/gaussians/*.ply", recursive=True)) or newest(
        glob.glob(f"{args.out_dir}/**/*.ply", recursive=True)
    )
    if not ply:
        raise SystemExit(f"no .ply found under {args.out_dir}; check save_gaussians in the config")

    # frame-0 intrinsics of the first trajectory (all trajectories share the input frame)
    fov_y = None
    width = height = None
    intr = newest(glob.glob(f"{args.gen_dir}/**/intrinsics/*.npz", recursive=True))
    intr_info: dict = {}
    if intr:
        d = np.load(intr)
        arr = d[d.files[0]]
        k = np.asarray(arr)
        k0 = k[0] if k.ndim >= 2 else k
        k0 = np.ravel(k0)
        # GEN3C stores (fx, fy, cx, cy) per frame
        if k0.size >= 4:
            fx, fy, cx, cy = map(float, k0[:4])
            width, height = int(round(cx * 2)), int(round(cy * 2))
            fov_y = math.degrees(2 * math.atan(height / (2 * fy)))
            intr_info = {"fx": fx, "fy": fy, "cx": cx, "cy": cy, "file": intr}
    pose = newest(glob.glob(f"{args.gen_dir}/**/pose/*.npz", recursive=True))

    bundle = Path(args.bundle_dir) / args.id
    bundle.mkdir(parents=True, exist_ok=True)
    # Lyra's "gaussians_*.ply" is a torch.save archive, not a PLY: convert to a real 3DGS PLY
    import subprocess, sys as _sys
    subprocess.run([_sys.executable, str(Path(__file__).with_name("lyra_pt_to_ply.py")), ply, str(bundle / "splat.ply")], check=True)
    src = bundle / ("source" + args.image.suffix.lower())
    shutil.copy2(args.image, src)
    if intr:
        shutil.copy2(intr, bundle / "intrinsics_frame0.npz")
    if pose:
        shutil.copy2(pose, bundle / "poses_traj0.npz")

    manifest = {
        "id": args.id,
        "name": args.id,
        "generator": "lyra",
        "splat": {"url": "./splat.ply", "convention": "opencv", "lod": True},
        "metric": {"scaleFactor": 1.0, "groundPlaneOffset": 0.0},
        "source": {"image": f"./{src.name}", "width": width, "height": height, "fovY": fov_y},
        "sourceCamera": None,
        "lyra": {"ply": ply, "intrinsics": intr_info, "poses": pose, "note": "world frame == input camera frame (identity w2c), OpenCV convention"},
        "notes": "Generated by pipelines/lyra/run_lyra.sh (NVIDIA Lyra 1.0). Photographer = splat origin looking +z_opencv, fovY from MoGe intrinsics.",
    }
    (bundle / "world.json").write_text(json.dumps(manifest, indent=2))
    print(f"bundle -> {bundle}\n  ply: {ply}\n  fovY: {fov_y}\n  size: {width}x{height}")


if __name__ == "__main__":
    main()
